Repository javascript-project-3/project-JS-3, pull requests merged in 2023-08, with the labels that each got.

#49 Feat: 메인 페이지 프로그램별 슬라이드 html 및 JS 구현
  client/index.html
  client/js/slider.js
  client/lib/main.js
  client/server/db/program.json
Labels: 💻CSS, 💻기능추가, 💻HTML, 💻JavaScript

#51 Loginpage
  client/css/tailwind.css
  client/findId.html
  client/findPw.html
  client/join.html
  client/js/login.js
  client/login.html
Labels: 💻JavaScript

#53 feat: 메인 페이지 프로그램별 슬라이드 구현
  client/index.html
  client/js/slider.js
  client/lib/main.js
Labels: 💻CSS, 💻기능추가, 💻HTML, 💻JavaScript

#54 feat: 로그인페이지 js추가
  client/findId.html
  client/findPw.html
  client/image/login/eye.png
  client/js/find.js
  client/js/login.js
  client/login.html
  server/db/data.json
Labels: 💻개발공통, 💻기능추가, 💻JavaScript

#58 style: 이미지파일 경로 변경
  client/join.html
  client/login.html
Labels: 💻JavaScript

#59 feat: 로그인 페이지 js작업 완료
  client/js/login.js
Labels: 💻JavaScript

#60 [JS] header, landing, join js 파일 완성
  client/header.html
  client/join.html
  client/js/header.js
  client/js/join.js
  client/js/landing.js
  client/landing.html
Labels: 💻JavaScript

#62 Index
  README.md
  client/css/tailwind.css
  client/index.html
  client/js/layout.js
  client/js/slider.js
  client/lib/main.js
  client/server/db/program.json
  index.html
  server/db/data.json
  src/scss/base/_default.scss
  src/scss/base/_index.scss
  src/scss/base/_normalize.scss
  src/scss/base/_reset.scss
  src/scss/components/_button.scss
  src/scss/components/_form.scss
  src/scss/components/_index.scss
  src/scss/index.scss
  src/scss/layout/_findId.scss
  src/scss/layout/_findPw.scss
  src/scss/layout/_footer.scss
  src/scss/layout/_header.scss
  src/scss/layout/_index.scss
  src/scss/layout/_join.scss
  src/scss/layout/_landing.scss
  src/scss/layout/_layout.scss
  src/scss/layout/_login.scss
  src/scss/layout/_logout.scss
  src/scss/layout/_profile.scss
  src/scss/layout/_search.scss
  src/scss/utils/_a11y.scss
  src/scss/utils/_color.scss
  src/scss/utils/_flexbox.scss
  src/scss/utils/_index.scss
  src/scss/utils/_media-query.scss
  src/scss/utils/_mixin.scss
  src/scss/utils/_sprites.scss
  src/scss/utils/_unit.scss
  src/style/index.css
  src/style/index.css.map
Labels: 📑문서, 💻성능향상, 💻개발공통, 💻CSS, 💻기능추가, 💻HTML, 💻JavaScript

#63 feat. 프로필 초기 페이지 작성 완료
  client/js/login.js
  client/js/profile_init.js
Labels: 💻성능향상, 💻JavaScript

#66 Index
  client/header.html
  client/index.html
  client/js/header.js
  client/js/layout.js
  client/js/login.js
  client/lib/main.js
  client/server/db/data.json
Labels: 📑문서, 💻성능향상, 💻버그수정, 💻CSS, 💻HTML, 💻JavaScript

#68 [js] 프로필 전환 작업
  client/header.html
  client/js/header.js
  client/js/profile_select.js
Labels: 💻성능향상, 💻버그수정, 💻기능추가, 💻JavaScript

#69 2차 배포
  client/header.html
  client/index.html
  client/js/header.js
  client/js/layout.js
  client/js/login.js
  client/js/profile_select.js
  client/lib/main.js
  client/server/db/data.json
Labels: 💻개발공통

#70 Index
  client/css/main.css
  client/css/tailwind.css
  client/index.html
  client/js/header.js
  client/js/profile.js
  client/js/profile_init.js
  client/js/profile_select.js
  client/js/search.js
  client/search.html
  tailwind.config.js
Labels: 💻성능향상, 💻버그수정

#72 docs: data JSON 파일 데이터 추가
  client/server/db/data.json
Labels: 📑문서

#74 fix: 회원가입 js 이미지 경로 수정
  client/js/join.js
Labels: 💻JavaScript

#75 Develop
  client/js/join.js
Labels: 💻JavaScript

#78 Index
  client/js/header.js
  client/js/test.js
  client/lib/dom/index.js
  client/server/db/data.json
  client/test.html
  db-1690898162278.json
Labels: 📑문서, 💻버그수정, 💻JavaScript

#89 Index
  client/js/slider.js
  client/lib/main.js
Labels: 💻JavaScript

#91 [리팩토링] 로그아웃 페이지
  README.md
  client/js/logout.js
Labels: 💻JavaScript

#92 Develop
  client/js/logout.js
  client/js/slider.js
  client/lib/main.js
Labels: 💻성능향상, 💻JavaScript

#94 Index
  client/css/main.css
  client/js/header.js
  client/js/landing.js
  client/js/layout.js
  client/js/slider.js
Labels: 💻성능향상, 💻버그수정, 💻JavaScript

#95 Develop
  client/css/main.css
  client/js/header.js
  client/js/landing.js
  client/js/layout.js
  client/js/slider.js
Labels: 💻버그수정, 💻JavaScript

#96 [리팩토링] 로그아웃 페이지 버튼 영역 및 리드미 로그인 정보 수정
  README.md
  client/logout.html
Labels: 💻버그수정, 💻HTML

#97 Develop
  README.md
  client/logout.html
Labels: 📑문서, 💻CSS
