Repository javascript-project-3/project-JS-3, pull requests merged in 2023-07, with the labels that each got.

#18 style: 메인페이지 CSS 작업
  client/index.html
Labels: fixed

#19 Style: 랜딩페이지, 헤더, 푸터 CSS 수정
  client/footer.html
  client/header.html
  client/landing.html
Labels: enhancement

#22 design: 메인 페이지 레이아웃 세팅
  client/index.html
Labels: enhancement

#23 Style: 랜딩페이지 CSS 수정
  client/landing.html
Labels: enhancement

#32 Index
  client/index.html
  client/js/layout.js
  client/js/slider.js
  client/lib/main.js
  client/server/db/program.json
Labels: 💻성능향상, 💻CSS, 💻기능추가, 💻HTML, 💻JavaScript

#34 logout, search, profile+profile_select 페이지 작업
  client/css/tailwind.css
  client/js/logout.js
  client/js/profile.js
  client/js/profile_select.js
  client/js/search.js
  client/lib/dom/index.js
  client/logout.html
  client/profile.html
  client/profile_select.html
  client/search.html
  server/db/data.json
  server/db/users.json
  tailwind.config.js
Labels: 💻성능향상, 😿SOS, 💻CSS, 💻기능추가, 💻HTML, 💻JavaScript

#37 profile+profile_select 모바일 뷰포트 작업
  client/js/profile.js
  client/js/profile_select.js
  client/profile.html
  client/profile_select.html
Labels: 😿SOS, 💻버그수정, 💻CSS

#48 [js] 프로필 및 검색 영역 페이지 작업
  client/js/profile.js
  client/js/profile_select.js
  client/js/search.js
  server/db/data.json
Labels: 💻성능향상, 💻버그수정, 💻JavaScript
